### ISSUE TITLE
go install results in a binary that panics

### ISSUE THREAD

**Issue by zapotah** [icedream/irc-medialink#62]
Running "go install github.com/icedream/irc-medialink@latest" or "go install github.com/icedream/irc-medialink@master" results in a binary that panics.

panic: template: pattern matches no files: `*.tpl`

goroutine 1 [running]:
text/template.Must(...)
        /usr/lib/go-1.18/src/text/template/helper.go:25
main.init()
        /opt/medialink/go/pkg/mod/github.com/icedream/irc-medialink@v1.1.3/templates.go:100 +0x7de

---

Either theres some dependencies that are not documented or this is something to do with 1.18.1.
Distro ubuntu 22.04.1 kernel 5.15

**Comment by zapotah** [comment]
Same issue with 1.19.3

**Comment by icedream** [comment]
The binary needs the main.tpl file in the working directory, it does not get compiled into the binary to allow for changes to be done to the template without having to recompile.
